---
permalink: task_active_iq_replication.html 
sidebar: sidebar 
keywords: solidfire, active, iq, replication 
summary: En savoir plus sur la page réplication dans SolidFire Active IQ. 
---
= La réplication
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La page *Replication*, disponible dans le panneau latéral d'un cluster sélectionné, fournit des informations sur les paires de clusters et les paires de volumes.

En savoir plus sur les pages paires de clusters et de volumes :

* <<cluster_pairs,Paires de clusters>>
* <<volume_pairs,Paires de volume>>
* <<snapmirror_endpoints,Terminaux SnapMirror>>
* <<snapmirror_relationships,Relations SnapMirror>>




== Paires de clusters

Sur la page *Replication* > *Cluster paires* pour un cluster sélectionné, vous pouvez afficher les informations suivantes sur les paires de clusters.

[cols="30,70"]
|===
| En-tête | Description 


| ID de paire de clusters | Numéro d'ID indiqué lors de la création de la paire de clusters. 


| Nom du cluster distant | Nom du cluster distant de la paire. 


| MVIP distant | IP virtuelle de gestion du cluster distant. 


| Réplication de volumes | Représente le nombre de volumes répliqués sur le cluster apparié. 


| État | État de la paire cluster. 


| UUID | Identifiant unique universel. 
|===


== Paires de volume

Sur la page *réplication* > *paires de volumes* pour un cluster sélectionné, vous pouvez afficher les informations suivantes sur les paires de volumes.

[cols="30,70"]
|===
| En-tête | Description 


| ID du volume | Numéro d'ID indiqué lors de la création du volume. 


| ID de compte | ID du compte attribué au volume. 


| État du volume | État du volume en cours de réplication. 


| Mode de réplication | Type de mode sélectionné pour la paire de volumes. 


| Direction  a| 
Indique la direction des données de volume :

* Source : indique que les données sont écrites sur une cible hors du cluster.
* Cible : indique que les données sont écrites sur le volume local à partir d'une source externe.




| Délai asynchrone  a| 
Durée écoulée depuis la dernière synchronisation du volume avec le cluster distant. Si le volume n'est pas apparié, il s'agit de la valeur NULL.


NOTE: Un volume cible dans un état de réplication actif a toujours un délai asynchrone de 0 (zéro). Les volumes cibles reconnaissent le système lors de la réplication et peuvent supposer que le délai asynchrone est à tout moment précis.



| Cluster distant | Nom du cluster distant sur lequel réside le volume. 


| ID du volume distant | ID de volume du volume sur le cluster distant. 
|===


== Terminaux SnapMirror

Sur la page *Replication* > *SnapMirror Endpoints* d'un cluster sélectionné, vous pouvez afficher les informations suivantes sur les terminaux SnapMirror.

[cols="30,70"]
|===
| En-tête | Description 


| ID de point final | Le numéro d'identification du point final. 


| Nom du cluster distant | Nom du cluster distant de la paire. 


| IP de gestion de cluster | Adresse IP de gestion du cluster. 


| IPS | Plage d'adresses IP de réseau virtuel utilisées pour le réseau virtuel. 


| Relations | Nombre de relations configurées pour un noeud final. 


| État | Indique si le point final est actuellement connecté ou non. Il a une valeur de *connecté* ou *déconnecté*. 
|===


== Relations SnapMirror

Sur la page *Replication* > *SnapMirror Relationships* d'un cluster sélectionné, vous pouvez afficher les informations suivantes sur les relations SnapMirror.

[cols="30,70"]
|===
| En-tête | Description 


| ID de point final | Le numéro d'identification du point final. 


| Volume source | ID de volume de la source. 


| Cluster de destination | Nom du cluster de destination dans la relation SnapMirror. 


| Volume de destination | Nom du volume de destination dans la relation SnapMirror. 


| État  a| 
État de la relation de symétrie. Il peut avoir trois valeurs possibles :

* Non initialisé : le volume de destination n'est pas initialisé.
* Snapmirrored : le volume de destination est initialisé et est prêt à recevoir les mises à jour SnapMirror.
* Broken-off : le volume de destination est en lecture-écriture et des snapshots sont présents.




| État  a| 
Si la relation est actuellement saine, elle peut avoir une valeur de *sain* ou *malsain*.


NOTE: Lorsqu'une mise à jour manuelle ou planifiée échoue ou est abandonnée, ou que la dernière mise à jour planifiée est retardée, il peut en résulter une valeur *malsaine*. Le champ *Détails* suivant l'état affiche la raison de l'état *malsain*.



| Type de relation  a| 
Type de relation SnapMirror.


NOTE: Sur les systèmes SolidFire, cette valeur est toujours définie sur `extended_data_protection`. Les systèmes NetApp disposent d'autres types de relations valides qui ne s'appliquent pas dans le cas des systèmes SolidFire.



| État  a| 
L'état du cluster :

* Intégrité : aucune erreur critique n'est associée au cluster.
* Offline : impossible d'accéder au cluster. Sélectionnez le lien pour afficher le journal des erreurs.
* Défaut : des erreurs sont associées à ce cluster. Sélectionnez le lien pour afficher le journal des erreurs.




| Détails | Informations permettant d'identifier la relation SnapMirror 
|===


== Trouvez plus d'informations

* https://www.netapp.com/support-and-training/documentation/["Documentation produit NetApp"^]
* https://docs.netapp.com/us-en/ontap/element-replication/index.html["Réplication entre le logiciel NetApp Element et ONTAP"^]

